#spring.application.name=practice-SpringAop

spring:
  application:
    name: practice-SpringAop
  datasource:
    url: jdbc:h2:./empDB
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2


server:
  port: 8087

